---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: xyz-git-src
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://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@github.com/gitops-lcm/xyz-fin.git