# cluster_calico.yaml
---
- name: k8 cluster cni init
  # become_user: "{{ ansible_user }}"
  # become: true
  vars:
    cp_host: "k8smaster"
  tags:
    - flannel
  block:
    - name: Install Flannel cni
      ansible.builtin.shell:
        cmd: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
      delegate_to: "{{ cp_host }}"
      # become: true
      when: "cp_host in inventory_hostname"
      changed_when: false

  rescue:
    - name: Handle errors during cni init
      ansible.builtin.debug:
        msg: ":: CNI ERROR ::"
