# cluster_init.yaml
---
- name: k8 cluster control plane init
  become: true
  become_user: root
  vars:
    cp_host: "k8smaster"
  tags:
    - init
  block:
    - name: Initialize the control plane
      ansible.builtin.shell:
        cmd: >
          sudo kubeadm init
          --control-plane-endpoint 130.211.215.39
          --apiserver-advertise-address 130.211.215.39
          --service-cidr 192.168.200.0/24
          --pod-network-cidr 192.168.210.0/24
          | tee kubeadm-init.out
      delegate_to: "{{ cp_host }}"
      when: "cp_host in inventory_hostname"
      changed_when: false

  rescue:
    - name: Handle errors during cp init
      ansible.builtin.debug:
        msg: ":: CP INIT ERROR ::"
