---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xyz-kust-vote
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: vote
    namespace: xyz-fin-ns
  interval: 1m0s
  path: ./vote
  prune: true
  sourceRef:
    kind: GitRepository
    name: xyz-git-src
  timeout: 2m0s
  targetNamespace: xyz-fin-ns