# flux_monitor.yaml
---
- name: patch flux_monitor service
  tags:
    - flux_monitor
  vars:
    ops_host: "ops"
  block:
    - name: Suspend monitoring-controllers Kustomization
      ansible.builtin.shell:
        cmd: >
          flux suspend kustomization monitoring-controllers
      delegate_to: "{{ ops_host }}"
      when: ops_host in inventory_hostname
      changed_when: false

    - name: Patch kube-prometheus-stack-grafana service to NodePort
      ansible.builtin.shell:
        cmd: >
          kubectl patch service kube-prometheus-stack-grafana -p '{"spec":{"type": "NodePort"}}' -n monitoring
      delegate_to: "{{ ops_host }}"
      when: ops_host in inventory_hostname
      changed_when: false

  rescue:
    - name: Handle errors during kust crds
      ansible.builtin.debug:
        msg: ":: PATCH SERVICE ERROR :: "


# flux suspend kustomization kube-prometheus-stack
# kubectl patch service kube-prometheus-stack-grafana -p '{"spec":{"type": "NodePort"}}' -n monitoring
