# flux_monitor.yaml
---
- name: patch flux_monitor service
  tags:
    - flux_monitor
  vars:
    ops_host: "ops"
  block:
    - name: Wait for 60 seconds - spin up time to monitor pods
      ansible.builtin.pause:
        seconds: 60

    - name: Patch the kube-prometheus-stack-grafana service
      kubernetes.core.k8s:
        state: present
        namespace: monitoring
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kube-prometheus-stack-grafana
          spec:
            type: NodePort
      delegate_to: "{{ ops_host }}"
      when: ops_host in inventory_hostname

    - name: Wait for 60 seconds after patch - spin up time to monitor pods
      ansible.builtin.pause:
        seconds: 60

    - name: Patch kube-prometheus-stack-grafana service to NodePort
      ansible.builtin.shell:
        cmd: >
          kubectl patch service kube-prometheus-stack-grafana -p '{"spec":{"type": "NodePort"}}' -n monitoring
      delegate_to: "{{ ops_host }}"
      when: ops_host in inventory_hostname
      changed_when: false

  rescue:
    - name: Handle errors during kust crds
      ansible.builtin.debug:
        msg: ":: PATCH SERVICE ERROR :: "
        
# this patch may not work - must check manually using ops machine

# kubectl patch service kube-prometheus-stack-grafana -p '{"spec":{"type": "NodePort"}}' -n monitoring
