# k8s_secret.yaml
---
- name: k8s secret for slack_url
  tags:
    - k8s_secret
  vars:
    ops_host: "ops"
    slack_url: "https://hooks.slack.com/services/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"
  block:
    - name: Create slack-url secret using kubectl
      ansible.builtin.shell: |
        kubectl create secret generic slack-url \
          --from-literal=address={{ slack_url }} \
          -n flux-system
      changed_when: false
      register: create_secret_output

  rescue:
    - name: Handle errors during kust crds
      ansible.builtin.debug:
        msg: ":: k8S SECRET ERROR :: "
