name: Manual Destroy Workflow

on:
  workflow_dispatch:

jobs:
  destroy_infra:
    name: 'Destroy Infra Job'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: gitops-poc-1
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        working-directory: /home/runner/work/gitops-poc/gitops-poc/
        run: gcloud auth activate-service-account --key-file=./resources/gitops-poc-1-0b406afbb75c.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan -input=false

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan
