name: gitops IaC CaC Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  infra:
    name: 'gitops IaC CaC job'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terrform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan

    - name: Terraform Destroy
      if: failure()
      run: terraform destroy -auto-approve

    - name: Get Terraform Outputs
      id: outputs
      run: |
        echo "k8smaster_public_ip=$(terraform output -raw k8smaster_public_ip)" >> $GITHUB_ENV
        echo "k8sworker1_public_ip=$(terraform output -raw k8sworker1_public_ip)" >> $GITHUB_ENV
        echo "ops_public_ip=$(terraform output -raw ops_public_ip)" >> $GITHUB_ENV
        echo "ssh_user=$(terraform output -raw ssh_user)" >> $GITHUB_ENV
        
    - name: Save Terraform State
      run: mv terraform.tfstate terraform_state.tfstate

    - name: Debug Terraform State
      run: cat terraform_state.tfstate

    - name: Upload Terraform State
      uses: actions/upload-artifact@v3
      with:
        name: terraform-state
        path: terraform_state.tfstate

    - name: Save Output Variables
      run: |
        echo "k8smaster_public_ip=${{ env.k8smaster_public_ip }}" >> terraform_outputs.env
        echo "k8sworker1_public_ip=${{ env.k8sworker1_public_ip }}" >> terraform_outputs.env
        echo "ops_public_ip=${{ env.ops_public_ip }}" >> terraform_outputs.env
        echo "ssh_user=${{ env.ssh_user }}" >> terraform_outputs.env

    - name: Debug Output Variables
      run: cat terraform_outputs.env

    - name: Upload Output Variables
      uses: actions/upload-artifact@v3
      with:
        name: terraform-outputs
        path: terraform_outputs.env
          
    - name: Update Inventory File
      run: |
        sed -i "s/k8smaster ansible_host=.*/k8smaster ansible_host=${{ env.k8smaster_public_ip }} ansible_user=${{ env.ssh_user }}/" inventory.ini
        sed -i "s/k8sworker1 ansible_host=.*/k8sworker1 ansible_host=${{ env.k8sworker1_public_ip }} ansible_user=${{  env.ssh_user }}/" inventory.ini
        sed -i "s/ops ansible_host=.*/ops ansible_host=${{ env.ops_public_ip }} ansible_user=${{  env.ssh_user }}/" inventory.ini

    - name: Terraform Destroy
      if: failure()
      run: terraform destroy -auto-approve
      
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
    - name: Add known hosts
      run: |
        ssh-keyscan -H ${{ env.k8smaster_public_ip }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ env.k8sworker1_public_ip }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ env.ops_public_ip }} >> ~/.ssh/known_hosts
      
    - name: Run k8s_playbook
      run: ansible-playbook k8s_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Run ops_playbook
      run: ansible-playbook ops_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Run notify_playbook
      run: ansible-playbook notify_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Set up Git user
      run: |
        git config --global user.email "eashin.matubber@ericsson.com.com"
        git config --global user.name "Eashin Matubber"

    - name: Clone flux-infra repository
      run: git clone https://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@github.com/gitops-lcm/flux-infra.git /home/runner/work/gitops-poc/flux-infra

    - name: Copy Monitoring Directory
      run: cp -r /home/runner/work/gitops-poc/gitops-poc/resources/monitoring /home/runner/work/gitops-poc/flux-infra

    - name: Copy flux operator CRDs to flux-infra
      run: cp /home/runner/work/gitops-poc/gitops-poc/resources/crds/fluxops/* /home/runner/work/gitops-poc/flux-infra/clusters/ops/

    - name: Git add changes
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git add .

    - name: Git commit changes
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git commit -m "updated flux ops crds"

    - name: Git push changes to main branch
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git push origin main

    - name: Wait for 30 seconds
      run: sleep 30

    - name: Copy flux deployment CRDs to flux-infra
      run: cp /home/runner/work/gitops-poc/gitops-poc/resources/crds/deploy/* /home/runner/work/gitops-poc/flux-infra/clusters/ops/

    - name: Git add changes
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git add .

    - name: Git commit changes
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git commit -m "updated flux deploy crds"

    - name: Git push changes to main branch
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: git push origin main

    - name: Wait for 60 seconds
      run: sleep 60
    
    - name: Run patch_playbook
      working-directory: /home/runner/work/gitops-poc/gitops-poc/
      run: ansible-playbook patch_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519
   
    - name: Delete Repository
      if: failure()
      run: terraform destroy -auto-approve

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
