name: gitops Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  infra:
    name: 'gitops IaC CaC job'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
        terraform_wrapper: false

    - name: Terraform Init
      run: |
        terraform init
        terraform plan -out=tfplan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan

    - name: Get Terraform Outputs
      id: outputs
      run: |
        echo "k8smaster_public_ip=$(terraform output -raw k8smaster_public_ip)" >> $GITHUB_ENV
        echo "k8sworker1_public_ip=$(terraform output -raw k8sworker1_public_ip)" >> $GITHUB_ENV
        echo "ops_public_ip=$(terraform output -raw ops_public_ip)" >> $GITHUB_ENV
        echo "ssh_user=$(terraform output -raw ssh_user)" >> $GITHUB_ENV

    - name: Update Inventory File
      run: |
        sed -i "s/k8smaster ansible_host=.*/k8smaster ansible_host=${{ env.k8smaster_public_ip }} ansible_user=${{ env.ssh_user }}/" inventory.ini
        sed -i "s/k8sworker1 ansible_host=.*/k8sworker1 ansible_host=${{ env.k8sworker1_public_ip }} ansible_user=${{ env.ssh_user }}/" inventory.ini
        sed -i "s/ops ansible_host=.*/ops ansible_host=${{ env.ops_public_ip }} ansible_user=${{ env.ssh_user }}/" inventory.ini

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add known hosts
      run: |
        ssh-keyscan -H ${{ env.k8smaster_public_ip }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ env.k8sworker1_public_ip }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ env.ops_public_ip }} >> ~/.ssh/known_hosts

    - name: Run k8s_playbook
      run: ansible-playbook k8s_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Run ops_playbook
      run: ansible-playbook ops_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Run notify_playbook
      run: ansible-playbook notify_playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519

    - name: Git config for runner
      run: |
        git config --global user.email "eashin.matubber@ericsson.com"
        git config --global user.name "Eashin Matubber"

    - name: Clone flux-infra repository and place monitor
      run: |  
        git clone https://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@github.com/gitops-lcm/flux-infra.git /home/runner/work/gitops-poc/flux-infra
        cp -r /home/runner/work/gitops-poc/gitops-poc/resources/monitoring /home/runner/work/gitops-poc/flux-infra
        cp /home/runner/work/gitops-poc/gitops-poc/resources/crds/fluxops/* /home/runner/work/gitops-poc/flux-infra/clusters/ops/

    - name: Git push monitor and flux-ops crds
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: |
        git add .
        git commit -m "updated flux ops crds"
        git push origin main
        sleep 30

    - name: Copy flux deployment CRDs to flux-infra
      run: cp /home/runner/work/gitops-poc/gitops-poc/resources/crds/deploy/* /home/runner/work/gitops-poc/flux-infra/clusters/ops/

    - name: Git push deployment crds
      working-directory: /home/runner/work/gitops-poc/flux-infra
      run: |
        git add .
        git commit -m "updated flux deploy crds"
        git push origin main
        sleep 30

    - name: Run patch_playbook
      working-directory: /home/runner/work/gitops-poc/gitops-poc/
      run: ansible-playbook patch_playbook.yaml -vvv
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_REMOTE_USER: ${{ env.ssh_user }}
        ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/id_ed25519
        
    - name: Terraform Destroy
      if: failure()
      run: terraform destroy -auto-approve
 
